### ISSUE TITLE
Unknown Middleware error

### ISSUE THREAD

**Issue by muhammedjenos** [stephenkr/nuxt-password-protect#11]
Followed the documentation to the T
just wanted to protect one page, so used middleware: ["password-protect"] in page exports,
and i get this error. Any hint?

![image](https://user-images.githubusercontent.com/2158510/81494847-efa07a00-92bc-11ea-94b4-68e4218b6a52.png)

**Comment by stephenkr** [comment]
Hi, @muhammedjenos thank you for using the module.

This can happen if you have forgotten to add `nuxt-password-protect` to `modules` in the nuxt config file.

I have updated the example and the documentation to better highlight this.

You can see the example here https://github.com/stephenkr/nuxt-password-protect/blob/master/examples/demo/nuxt.config.js#L37

Hopefully, this is the reason. All the best.

**Comment by muhammedjenos** [comment]
I did that proper as below:

 modules: [
    // Doc: https://axios.nuxtjs.org/usage
    '@nuxtjs/axios',
    // Doc: https://github.com/nuxt-community/dotenv-module
    '@nuxtjs/dotenv',
    // https: //github.com/nuxt-community/svg-module
    "@nuxtjs/svg",
    // https: //github.com/LinusBorg/portal-vue
    'portal-vue/nuxt',
   
    ['nuxt-password-protect']
  ],

  //   Password protect pages options 
  passwordProtect: {
    formPath: '/password',
    password: 'test123',
    tokenSeed: 101010,
    queryString: '_pw',
    cookieName: '_password',
    cookie: {
      prefix: '',
      expires: 5
    }
  },

**Comment by stephenkr** [comment]
Hi @muhammedjenos 

Can you try this? Inside your nuxt config file.
```js
module.exports = {
  modules: [
    // Doc: https://axios.nuxtjs.org/usage
    '@nuxtjs/axios',
    // Doc: https://github.com/nuxt-community/dotenv-module
    '@nuxtjs/dotenv',
    // https: //github.com/nuxt-community/svg-module
    "@nuxtjs/svg",
    // https: //github.com/LinusBorg/portal-vue
    'portal-vue/nuxt',
    // Nuxt password protect
    'nuxt-password-protect'
  ],

  // Password protect pages options
  passwordProtect: {
    formPath: '/password',
    password: 'test123',
    tokenSeed: 101010,
    queryString: '_pw',
    cookieName: '_password',
    cookie: {
      prefix: '',
      expires: 5
    }
  }
}
```

**Comment by muhammedjenos** [comment]
Hmm.. Same issue.
For more clarity, I am testing this in dev server and the package is added as dependencies in package.json.

Not sure if I miss any steps, which are as below

- npm install nuxt-password-protect
- Add the package in the modules as 'nuxt-password-protect'
- Add the options in nuxt.config.js
- Add in the page  middleware: ["password-protect"],

Guess thats it? Still no go. :(

**Comment by stephenkr** [comment]
Hi @muhammedjenos that's quite strange, I have created a new project from scratch and it all works.

Here are the changes:
```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "My superb Nuxt.js project",
  "author": "Test",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate"
  },
  "dependencies": {
    "cross-env": "^5.2.0",
    "nuxt": "^2.4.0",
    "nuxt-password-protect": "^1.0.5"
  },
  "devDependencies": {
    "nodemon": "^1.18.9"
  }
}
```

```js
const pkg = require('./package')

module.exports = {
  mode: 'universal',

  server: {
    port: 4003
  },

  /*
  ** Headers of the page
  */
  head: {
    title: pkg.name,
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: pkg.description }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },

  /*
  ** Customize the progress-bar color
  */
  loading: { color: '#fff' },

  /*
  ** Global CSS
  */
  css: [
  ],

  /*
  ** Plugins to load before mounting the App
  */
  plugins: [
  ],

  /*
  ** Nuxt.js modules
  */
  modules: [
    'nuxt-password-protect'
  ],

  passwordProtect: {
    formPath: '/password2',
    password: 'test123',
    tokenSeed: 101010,
    queryString: '_pw',
    cookieName: '_password',
    cookie: {
      prefix: '',
      expires: 5
    }
  },

  /*
  ** Build configuration
  */
  build: {
    /*
    ** You can extend webpack config here
    */
    extend(config, ctx) {
      
    }
  }
}

```

```vue
<template>
  <section class="container">
    testing
  </section>
</template>

<script>
import Logo from '~/components/Logo.vue'

export default {
  components: {
    Logo
  },
  middleware: ["password-protect"]
}
</script>

<style>

</style>

```

All setup using npm.

**Comment by muhammedjenos** [comment]
Thank you for the prompt replies. appreciated
I will set up a test project and see if it works. funny it says Middleware cant be found.

**Comment by stephenkr** [comment]
No problem thank you for letting me know so I can improve the module

Hopefully you get to the source of why.

In the module, the middleware is declared here, https://github.com/stephenkr/nuxt-password-protect/blob/master/lib/plugin.js#L6, for some reason this is not being executed or it is being overridden in your project.

**Comment by muhammedjenos** [comment]
I noticed my project wasn't recompiling when i edit the nuxt config. shut down everything and restarted the machine. and all working fine now. phew. Really miss the old html/css days of development. lol.

Thank you for the time Sir. Appreciated.

**Comment by stephenkr** [comment]
No problem, happy to help :)
