### ISSUE TITLE
Refreshing on protected dynamic page redirects to /password

### ISSUE THREAD

**Issue by robbylucia** [stephenkr/nuxt-password-protect#19]
Hi,

**Issue**
Direct URL entering OR refreshing a dynamic page in Nuxt results in a redirect to the password.vue page.

**Reproduction**

1. Install `nuxt-password-protect` either for the whole app or for this page we are making.
2. Create a folder in `pages`, for example: `user`
3. Create a dynamic page in that folder: `_user.vue`, which will look like `/pages/user/_user.vue`
4. Visit that page and enter the password when prompted. Now refresh the page. Also copy the URL and enter it again (visiting it directly), both of these methods result in being redirected to /password.

I was able to do a workaround but it's not ideal and I'm sure this is not expected behavior. Is this something I'm doing wrong, or something that may be fixed if this is an issue? Thanks!

**Comment by stephenkr** [comment]
Hi @robbylucia thank you for using this module. Also sorry I haven't replied in a while.

I'm struggling to reproduce the issue you have reported above, I'll have updated the example in this project to contain a dynamic path.

Could you try running it and seeing if the same issue happens? Please let me know, thank you.

The example can be found here https://github.com/stephenkr/nuxt-password-protect/tree/master/examples/demo
