### ISSUE TITLE
Infinite loop when protecting full website

### ISSUE THREAD

**Issue by sergiocastrovale** [stephenkr/nuxt-password-protect#21]
This is my config:

```javascript
  passwordProtect: {
    formPath: '/locked',
    password: 'testing',
    tokenSeed: 101010,
    queryString: '_pw',
    cookieName: '_locked',
    cookie: {
      prefix: '',
      expires: 5
    }
  },
```

I have a page named `locked.vue` in which I want the users to be forced to so that they can input the password. However, because the _whole website_ is protected by the middleware, this page is auto-redirecting to itself infinitely.

Adding `ignoredPaths: ['/locked']` doesn't seem to fix this either. What am I doing wrong?

**Comment by sergiocastrovale** [comment]
Finally found the issue. I am using `nuxt-i18n` to handle my dynamic, localized routes, so I had to disable the i18n prefix for this specific path (`/locked`):

```
// routes/index.js
export default {
  locked: false,
  ...
}
```

**Comment by stephenkr** [comment]
Hi @sergiocastrovale oh amazing, good find. Happy to hear you found the reason.
