### ISSUE TITLE
Toggling global protection from a process.env variable

### ISSUE THREAD

**Issue by sergiocastrovale** [stephenkr/nuxt-password-protect#22]
Is there anyway to achieve this? Let's say I have global protection like:

```
  router: {
    middleware: ['password-protect']
  },
  passwordProtect: {
    formPath: '/locked',
    password: 'testing',
    tokenSeed: 101010,
    queryString: '_pw',
    cookieName: '_locked',
    cookie: {
      prefix: '',
      expires: 5
    }
  },
```

This would always lock my entire website... Maybe we could have an additional option to enable  / disable the protection. Something like:

```
passwordProtect: {
    enabled: process.env.NODE_ENV === 'production', # this
    formPath: '/locked',
    password: 'testing',
    tokenSeed: 101010,
    queryString: '_pw',
    cookieName: '_locked',
    cookie: {
      prefix: '',
      expires: 5
    }
  },
```

Because otherwise we have no way to control if password protection is on/off, you'll have to change the code in order to do so.

**Comment by stephenkr** [comment]
Hi @sergiocastrovale sorry, it's been a while since I've checked the issues.

But yes this is a good idea, I'll prepare a PR to provide it.

**Comment by stephenkr** [comment]
Hi @sergiocastrovale the update has been published https://www.npmjs.com/package/nuxt-password-protect

Thanks again for suggesting the change.
