### ISSUE TITLE
Redirect to multiple form pages using internationalization

### ISSUE THREAD

**Issue by shuaibreeyaz** [stephenkr/nuxt-password-protect#28]
I'm using i18n to show users English and French pages. Is there a way to have multiple formPaths?

**Comment by LeonBuchner** [comment]
You can try to install my forked version:

https://github.com/LeonBuchner/nuxt-password-protect

Its working fine for me.

**Comment by LeonBuchner** [comment]
It will detect the curent i18n locale and append it before the formPath url

**Comment by stephenkr** [comment]
Hi @shuaibreeyaz sorry for only replying now, I'll think about an approach.

Do you have any suggestions on how you would like it to work?

**Comment by stephenkr** [comment]
Hi @shuaibreeyaz @nonlinercom and @LeonBuchner thank you for requesting this feature.

I have added a way to control the redirect logic using a Nuxt plugin, you can find it here https://github.com/stephenkr/nuxt-password-protect/pull/31

**Comment by LeonBuchner** [comment]
Thank you!

**Comment by stephenkr** [comment]
I'll close this issue since it's now working. Thank you again for requesting this feature.

**Comment by LeonBuchner** [comment]
Hey I have tested everything carefully now and its not really working.

1. When you click on the button to go to the password protected page, the previous Path is wrong and will redirect you back to front page after successfully entering the password.

2. When you visit the page which should be password protected directly the password form will show. When you go back to frontpage and visit the password protected page via button again it will be unlocked without password. This is only with the new i18n fix. Without it its working fine.

**Comment by stephenkr** [comment]
HI, @LeonBuchner thank you so much for testing it. I'll fix the issues you have noticed above.

I think they are more specific to the example project, but I'll investigate.

**Comment by LeonBuchner** [comment]
Any news here?
