### ISSUE TITLE
Can still access protected i18n pages when logged out

### ISSUE THREAD

**Issue by jackgregory** [stephenkr/nuxt-password-protect#43]
Hi,

**Issue**

Protected i18n pages or routes can be accessed when logged out.

Can reproduce this on the example site:

**Steps to reproduce:**

1. Login using any method
2. Change the url or navigate to https://nuxt-password-protect.netlify.app/fr/
3. Can see logged in page/content

I thought that setting the following in nuxt.config.js would fix this, but instead it causes the browser (chrome) to freeze as it tries a redirect.

```
router: {
   middleware: ["password-protect"],
},
```

**Comment by jackgregory** [comment]
Update, it was related to the example redirect plugin and this [return statement](https://github.com/stephenkr/nuxt-password-protect/blob/efbd2c3d5b0775e3a368ebe8cba532691c2d6fd6/examples/demo/plugins/setup-password-protect.js#L6) commenting this out now redirects all paths.

**Comment by stephenkr** [comment]
Hi, i am no longer actively extending this module. Thank you for reporting the issue.
