### ISSUE TITLE
Octal literals not allowed by strict linting

### ISSUE THREAD

**Issue by dev7ch** [stephenkr/nuxt-password-protect#7]
![image](https://user-images.githubusercontent.com/15183757/73608676-28e29300-45c6-11ea-94d2-e86e5559f476.png)

This could be solved very easy be starting with 1 instead of 0, 

e.g. `tokenSeed: 101010`

ofc this should be changed ;)

Question:

This token can be a String or INT, correct?

**Comment by stephenkr** [comment]
Hi @dev7ch, thank you for using the module and also thank you for contributing :)

Yep, you're right, the token seed can be a string or a number.

I'll fix the module now to remove the leading 0 since this was a mistake when first building the module.

Thank you again,

Stephen.

**Comment by stephenkr** [comment]
The Readme has been updated, thank you again.

Now closing this issue.

**Comment by dev7ch** [comment]
Thank you for the cool module, good work!
